In [0]:
#@title Default title textsdfsaf
from google.colab import drive
drive.mount('/content/drive')

In [0]:
!ls '/content/drive/My Drive/Colab Notebooks/ExpoFraud/data'

sample_submission.csv  test_transaction.csv  train_transaction.csv
test_identity.csv      train_identity.csv

In [0]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

# neural networks

import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

# metric
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve 

# parameters
random_seed = 1
train_size = 0.75
test_size = 0.25

In [0]:
df_identity_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ExpoFraud/data/train_identity.csv')
df_transaction_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ExpoFraud/data/train_transaction.csv')

df_identity_test = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ExpoFraud/data/test_identity.csv')
df_transaction_test = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ExpoFraud/data/test_transaction.csv')

In [0]:
df_transaction_train.head()

   TransactionID  isFraud  TransactionDT  ...  V337 V338  V339
0        2987000        0          86400  ...   NaN  NaN   NaN
1        2987001        0          86401  ...   NaN  NaN   NaN
2        2987002        0          86469  ...   NaN  NaN   NaN
3        2987003        0          86499  ...   NaN  NaN   NaN
4        2987004        0          86506  ...   0.0  0.0   0.0

[5 rows x 394 columns]

In [0]:
df_identity_train.head()

   TransactionID  id_01  ...  DeviceType                     DeviceInfo
0        2987004    0.0  ...      mobile  SAMSUNG SM-G892A Build/NRD90M
1        2987008   -5.0  ...      mobile                     iOS Device
2        2987010   -5.0  ...     desktop                        Windows
3        2987011   -5.0  ...     desktop                            NaN
4        2987016    0.0  ...     desktop                          MacOS

[5 rows x 41 columns]

In [0]:
df_transaction_train.isnull().sum()

TransactionID          0
isFraud                0
TransactionDT          0
TransactionAmt         0
ProductCD              0
                   ...
V335              508189
V336              508189
V337              508189
V338              508189
V339              508189
Length: 394, dtype: int64

In [0]:
df_transaction_train.describe()

       TransactionID        isFraud  ...           V338           V339
count   5.905400e+05  590540.000000  ...   82351.000000   82351.000000
mean    3.282270e+06       0.034990  ...     151.160542     100.700882
std     1.704744e+05       0.183755  ...    1095.034387     814.946722
min     2.987000e+06       0.000000  ...       0.000000       0.000000
25%     3.134635e+06       0.000000  ...       0.000000       0.000000
50%     3.282270e+06       0.000000  ...       0.000000       0.000000
75%     3.429904e+06       0.000000  ...       0.000000       0.000000
max     3.577539e+06       1.000000  ...  104060.000000  104060.000000

[8 rows x 380 columns]